ManageNotes/Components/CreditViewComponent.cs
using System.Threading.Tasks;
using ManageNotes.Services;
using ManageNotes.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace ManageNotes.Components
{
    public class CreditViewComponent:ViewComponent
    {
        private UserServices _userServices;

        public CreditViewComponent(UserServices userServices)
        {
            _userServices = userServices;
        }

        public async Task<IViewComponentResult> InvokeAsync(int userId)
        {
            var user =await _userServices.FindAsync(userId);
            var model = new CreditModel()
            {
                Amount = user.Credit
            };
            return View("_default", model);
        }
    }
}

ManageNotes/Controllers/PaymentController.cs
using System;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using ManageNotes.Data;
using ManageNotes.Services;
using Microsoft.AspNetCore.Mvc;
using Parbad;
using RestSharp;
using ManageNotes.Utils;

namespace ManageNotes.Controllers
{
    public class PaymentController : Controller
    {
        private ApplicationContext _applicationContext;
        private IOnlinePayment _onlinePayment;
        private PaymentServices _paymentServices;

        public PaymentController(IOnlinePayment onlinePayment, ApplicationContext applicationContext, PaymentServices paymentServices)
        {
            _onlinePayment = onlinePayment;
            _applicationContext = applicationContext;
            _paymentServices = paymentServices;
        }

        [HttpPost]
        public async Task<IActionResult> Pay(int amount)
        {
            var payment = new Payment()
            {
                Amount = amount,
                UserId = User.GetId()
            };
            var username = User.Claims.First(x => x.Type == ClaimTypes.Name).Value;
            
            var client = new RestClient("https://api.idpay.ir/v1.1/payment");
            var request = new RestRequest(Method.POST);
            request.AddParameter("X-API-KEY", "75f79830-1e02-42c6-a13d-a1da83d164c5");
            request.AddParameter("X-SANDBOX", 1);
            request.AddParameter("order_id", payment.Syst_Code);
            request.AddParameter("amount", payment.Amount);
            request.AddParameter("name", username);
            request.AddParameter("callback", "https://localhost:5001/payment/Verify"); //****** change for Use in IIS ******//

            var response =await client.ExecuteAsync(request);
            if (response.IsSuccessful && response.StatusCode==HttpStatusCode.Created)
            {
                var link=response.ResponseUri.AbsoluteUri;
                var id = response.Headers[12].Value.ToString();
                
                return Redirect(Path.Combine(link, id));
            }

            return Content(response.ErrorException.Message);
            
            //var id = response?.Headers[12].Value?.ToString();
            //return Redirect(Path.Combine(link, payment.Syst_Code));
        }

        [HttpGet]
        public IActionResult Verify()
        {
            return Content("in action");
        }
    }
}

ManageNotes/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using ManageNotes.Data;
using ManageNotes.Services;
using ManageNotes.ViewModel;
using Mapster;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using ManageNotes.Utils;

namespace ManageNotes.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private ApplicationContext _applicationContext;
        private UserServices _userServices;
        private IWebHostEnvironment _environment;

        public UserController(ApplicationContext applicationContext, UserServices userServices, IWebHostEnvironment environment)
        {
            _applicationContext = applicationContext;
            _userServices = userServices;
            _environment = environment;
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult LogIn()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> LogIn(LogInModel model)
        {
            var url = Request.Query["ReturnUrl"].ToString();
            if (ModelState.IsValid)
            {
                var user =await _userServices.GetUserWithUserNameAsync(model.UserName);
                if (user is null)
                {
                    ModelState.AddModelError("UserName","حسابی با این نام کاربری وجود ندارد.");
                    return View(model);
                }
                
                if (user.PassWord != model.PassWord.GetHash())
                {
                    ModelState.AddModelError("PassWord","رمز عبور اشتباه است.");
                    return View(model);
                }

                var model2 = user.Adapt<UserViewModel>();
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                    model2.GetPrincipal());

                /*if (!String.IsNullOrEmpty(url))
                {
                    var splited = url.SplitUrl();
                    return RedirectToAction(splited.actionName, splited.controllerName);
                }*/

                if (user.Role==TypeAccountEnum.Admin || user.Role==TypeAccountEnum.Owner)
                {
                    return RedirectToAction("IndexAdmins", "Admins");
                }
                
                return RedirectToAction("NoteIndex", "Note");
            }
            return View(model);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }
        
        [AllowAnonymous]
        [HttpGet]
        public IActionResult LogUp()
        {
            return View(new LogUpModel());
        }
        
        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> LogUp(LogUpModel model)
        {
            if (ModelState.IsValid)
            {
                if (await _userServices.IsExistUserWithUsernameAsync(model.UserName))
                    return Json(new {status = false, message = "نام کاربری تکراری است. یک نام جدید انتخاب کنید."});
                        
                User user = new User
                {
                    UserName = model.UserName,
                    PassWord = model.PassWord.GetHash(),
                };

                if (model.File is not null)
                {
                    var blackList = new[] {".c", ".bat", ".shell", ".cmd"};
                    var t = blackList.Any(x => x == model.File.ContentType);
                    if (t)
                        
                    
                    if (model.File.Length>(3*1024*1024))
                        return Json(new {status=false, message="حجم فایل نباید بیش از 3 مگابایت باشد."});
                    
                    user.Image =await model.File.GetArrayBytesAsync();
                }

                await _userServices.AddUserAsync(user);
                await _applicationContext.SaveChangesAsync();
                var u =await _applicationContext.Users.FirstOrDefaultAsync(x => x.UserName == model.UserName);

                u.Role = TypeAccountEnum.Member;
                if (User.IsInRole(TypeAccountEnum.Owner.GetNumberWithString()))
                {
                    u.Role = model.Role;
                }

                var rows=await _applicationContext.SaveChangesAsync();
                if (rows>0)
                {
                    if (User.Identity.IsAuthenticated  && !User.IsInRole(TypeAccountEnum.Member.GetNumberWithString()))
                        return Json(new {status=true, message="حساب کاربری با موفقیت ایجاد شد."});
                    
                    var u2 = u.Adapt<UserViewModel>();
                    var principal = u2.GetPrincipal();
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                        principal);
                    return RedirectToAction("NoteIndex", "Note");
                }
            }

            string s="";
            foreach (var value in ModelState.Values)
            foreach (ModelError error in value.Errors)
                s+=error.ErrorMessage;
            
            return Json(new {status=false, message=s});
        }
        
        public async Task<IActionResult> ShowImage(int id)
        {
            var user =await _userServices.FindAsync(id);
            if (user.Image is not null)
            {
                return new FileContentResult(user.Image, "image/jpeg");
            }

            var wwroot = _environment.WebRootPath;
            var path = Path.Combine(wwroot, "image", "UserDefualt.png");
            return new PhysicalFileResult(path, "image/png");
        }

        [HttpGet]
        public async Task<IActionResult> EditProfile(int id=-1)
        {
            var userId = User.GetId();
            if (id!=-1)
            {
                userId = id;
            }
            var user =await _userServices.FindAsync(userId);
            var model = new EditProfileModel()
            {
                UserName =user.UserName,
                Id=user.Id,
                Role = user.Role,
                Check = id
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditProfile(EditProfileModel model)
        {
            if (ModelState.IsValid)
            {
                var user =await _userServices.FindAsync(model.Id);
                var exist =await _userServices.IsExistUserWithUsernameAsync(model.UserName);
                model.Check = user.Id;
                
                if (user.UserName!=model.UserName && exist)
                    return Json(new {status = false, message = "نام کاربری تکراری است. یک نام جدید انتخاب کنید."});
                

                if (model.File is not null)
                {
                    var blacList = new [] {".c", ".bat", ".shell", ".cmd"};
                    var t = blacList.Any(x => x == model.File.ContentType);
                    if (t)
                        return Json(new {status = false, message = "آپلود فایل نامعتبر"});
                    
                    if (model.File.Length>(3*1024*1024))
                        return Json(new {status = false, message = "حجم فایل نباید بیش از 3 مگابایت باشد."});
                    
                    user.Image =await model.File.GetArrayBytesAsync();
                }
                
                user.UserName = model.UserName;
                if (User.IsInRole(TypeAccountEnum.Owner.GetNumberWithString()))
                {
                    user.Role = model.Role;
                }
                
                await _applicationContext.SaveChangesAsync();
                
                return Json(new {status = true, message = "تغییرات روی حساب کاربری اعمال شد."});
            }

            model.Check = 50;
            return Json(new {status = false, message = "خطا در اعمال تغییرات"});
        }

        [HttpGet]
        [Route("User/ChangePassword/{id}")]
        public IActionResult ChangePassword(int id)
        {
            return View(new ChangePassModel(){Id = id, Password = "12345678"});
        }
        
        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePassModel model)
        {
            if (ModelState.IsValid)
            {
                var user =await _userServices.FindAsync(model.Id);

                if (user is not null)
                {
                    if (User.GetRole() == (int)TypeAccountEnum.Member && user.PassWord != model.Password.GetHash())
                    {
                        ModelState.AddModelError("Password","رمز عبور فعلی درست نمی باشد.");
                        return View(model);
                    }

                    user.PassWord = model.NewPass.GetHash();
                    var rows=await _applicationContext.SaveChangesAsync();
                    if (rows>0)
                    {
                        model.State = 1;
                        ModelState.AddModelError("State", "رمز عبور با موفقیت تغییر کرد.");
                        user.SerialNo = Guid.NewGuid().ToString().Substring(0, 10);
                        return View(model);
                    }
                }
                }
            model.State = 2;
            ModelState.AddModelError("State", "خطا رد تغییر رمز عبور");
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteAccount(int id)
        {

ManageNotes/Views/Shared/Index.cshtml
@{
    ViewData["Title"] = "Managing Note System";
}

<div class="text-center">
    <h6 class="display-4">خوش آمدید</h6>
    <h5>سیستم مدیریت یاداشت ها و برنامه های روزانه</h5>
</div>

ManageNotes/Views/Shared/NoteIndex.cshtml
@using ManageNotes.Utils

@{
    ViewData["Title"] = "Note Page";
    Layout = "_LayoutNotes";
}

<div class="text-center">
    <p>Add, update and visit your notes</p>
    <br>
    
    <div class="jumbotron">
        @await Component.InvokeAsync("Credit", new{userId=User.GetId()})
        <br>
        <form method="post" asp-controller="Payment" asp-action="Pay">
            <div class="row">
                <div class="form-group col-md-8">
                    <input name="amount" class="form-control" type="text" placeholder="مبلغ">
                </div>
                <div class="col-md-4">
                    <button type="submit" class="btn btn-primary btn-block">پرداخت</button>
                </div>
            </div>
        </form>
    </div>
    
</div>

ManageNotes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - ManageNotes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/lib/iconic/font/css/open-iconic-bootstrap.min.css">
    @await RenderSectionAsync("CSSStyle",required:false)
    <style>
        body{
        font-family: 'Samim', Arial, sans-serif;
        direction: rtl;
        text-align: right;
        background-color: white;
        }
        header{
        background-color: #e2e3e5 !important;
        }
    </style>
</head>
<body>
<header>
    <div class="row">
        <div class="col-md-2">
            <img src="~/image/task-notes-icon.png" width="115px" height="115px">
        </div>
        <div class="col-md-7"></div>
        <div class="col-md-3" style="direction: ltr">
            <div>
                
            </div>
        </div>
    </div>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">سیستم مدیریت یادداشت</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a id="home" class="nav-link text-dark" asp-area="" 
                           asp-controller="Home" asp-action="Index"><span class="oi oi-home"></span>  خانه</a>
                    </li>
                    <li class="nav-item">
                        <a id="login" class="nav-link text-dark" asp-area=""
                           asp-controller="User" asp-action="LogIn"><span class="oi oi-account-login"></span>  ورود</a>
                    </li>
                    
                    <li class="nav-item">
                        <a id="logup" class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="LogUp">
                            <span class="oi oi-plus"></span>  ثبت نام</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - سیستم مدیریت یادداشت
    </div>
</footer>
<script src="~/lib/jquery/jquery-3.6.0.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)

<script>
if (self.location.pathname == '/'){
    document.getElementById('home').classList.add('active');
    }
else if (self.location.pathname == "/User/LogIn"){
         document.getElementById('login').classList.add('active');
         }
else if (self.location.pathname == "/User/LogUp"){
         document.getElementById('logup').classList.add('active');
         }
</script>

</body>
</html>

ManageNotes/Views/Shared/_LayoutAdmins.cshtml
@using ManageNotes.Data
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - ManageNotes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/lib/jquery/jquery-3.6.0.min.js">
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/lib/iconic/font/css/open-iconic-bootstrap.min.css">
    @await RenderSectionAsync("CSSStyle",required:false)
    <style>
        body{
        font-family: 'Samim', Arial, sans-serif;
        direction: rtl;
        text-align: right;
        background-color: white;
        }
        header{
        background-color: #e2e3e5 !important;
        }
        .center{
        display: flex !important;
        justify-content: center !important;
        align-items: center !important;
        direction: ltr !important;
        }
    </style>
</head>
<body>
<header>
    <div class="row">
        <div class="col-md-2">
            <img src="~/image/task-notes-icon.png" width="115px" height="115px">
        </div>
        <div class="col-md-7"></div>
        <div class="col-md-3" style="direction: ltr">
            <div>
                @await Component.InvokeAsync("User")
            </div>
        </div>
    </div>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Admins" asp-action="IndexAdmins">پنل مدیریت</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a id="home" class="nav-link text-dark" asp-area="" asp-controller="Admins" asp-action="IndexAdmins">
                            <span class="oi oi-home"></span>  خانه</a>
                    </li>
                    <li class="nav-item">
                        <a id="manageusers" class="nav-link text-dark" asp-area="" asp-controller="Admins" asp-action="ShowUsers">
                            <span class="oi oi-people"></span>  مدیریت کاربران</a>
                    </li>
                    @{
                        if (User.Identity.IsAuthenticated && User.IsInRole(TypeAccountEnum.Owner.GetNumberWithString()))
                        {
                            <li class="nav-item">
                                <a id="plus" class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="LogUp">
                                    <span class="oi oi-plus"></span>  اضافه کردن کاربر و ادمین</a>
                            </li>
                            <li class="nav-item">
                                <a id="manageadmins" class="nav-link text-dark" asp-area="" asp-controller="Admins" asp-action="ShowAdmins">
                                    <span class="oi oi-person"></span>  مدیریت ادمین ها</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a id="plus" class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="LogUp">
                                    <span class="oi oi-plus"></span>  اضافه کردن کاربر</a>
                            </li>
                        }
                    }
                    <li class="nav-item">
                        <a id="edit" class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="EditProfile">
                            <span class="oi oi-pencil"></span>  ویرایش حساب کاربری</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">
                            <span class="oi oi-account-logout"></span>  خروج</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - سیستم مدیریت یادداشت
    </div>
</footer>
<script src="~/lib/jquery/jquery-3.6.0.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)

<script>
if (self.location.pathname == '/Admins/IndexAdmins'){
    document.getElementById('home').classList.add('active');
    }
else if (self.location.pathname == '/Admins/ShowUsers'){
         document.getElementById('manageusers').classList.add('active');
         }
else if (self.location.pathname == '/User/LogUp'){
         document.getElementById('plus').classList.add('active');
         }
else if (self.location.pathname == '/Admins/ShowAdmins'){
         document.getElementById('manageadmins').classList.add('active');
         }
else if (self.location.pathname == '/User/EditProfile'){
         document.getElementById('edit').classList.add('active');
         }
</script>
</body>
</html>

ManageNotes/Views/Shared/_LayoutNotes.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - ManageNotes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/lib/jquery/jquery-3.6.0.min.js">
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/lib/iconic/font/css/open-iconic-bootstrap.min.css">
     @await RenderSectionAsync("CSSStyle",required:false)
    <style>
            body{
            font-family: 'Samim', Arial, sans-serif;
            direction: rtl;
            text-align: right;
            background-color: white;
            }
            header{
            background-color: #e2e3e5 !important;
            }
            .center{
            display: flex !important;
            justify-content: center !important;
            align-items: center !important;
            direction: ltr !important;
            }
        </style>
</head>
<body id="Body">
<header>
    <div class="row">
            <div class="col-md-2">
                <img src="~/image/task-notes-icon.png" width="115px" height="115px">
            </div>
            <div class="col-md-9"></div>
            <div class="col-md-1" style="direction: ltr">
                <div>
                    @await Component.InvokeAsync("User")
                </div>
            </div>
        </div>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Note" asp-action="NoteIndex">سیستم مدیریت یادداشت</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a id="home" class="nav-link text-dark" asp-area="" asp-controller="Note" asp-action="NoteIndex">
                            <span class="oi oi-home"></span>  خانه</a>
                    </li>
                    <li class="nav-item">
                        <a id="shownote" class="nav-link text-dark" asp-area="" asp-controller="Note" asp-action="ShowNotes"
                           asp-route-id="-1"><span class="oi oi-eye"></span>  نمایش یادداشت ها</a>
                    </li>
                    <li class="nav-item">
                        <a id="new" class="nav-link text-dark" asp-area="" asp-controller="Note" asp-action="New">
                            <span class="oi oi-plus"></span>  یادداشت جدید</a>
                    </li>
                    <li class="nav-item">
                        <a id="edit" class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="EditProfile">
                            <span class="oi oi-pencil"></span>  ویرایش حساب کاربری</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="LogOut">
                            <span class="oi oi-account-logout"></span>  خروج</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - سیستم مدیریت یادداشت
    </div>
</footer>
<script src="~/lib/jquery/jquery-3.6.0.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)

<script>
if (self.location.pathname == '/Note/NoteIndex'){
    document.getElementById('home').classList.add('active');
    }
else if (self.location.pathname == '/Note/ShowNotes/-1'){
         document.getElementById('shownote').classList.add('active');
         }
else if (self.location.pathname == '/Note/New'){
         document.getElementById('new').classList.add('active');
         }
else if (self.location.pathname == '/User/EditProfile'){
         document.getElementById('edit').classList.add('active');
         }
</script>
</body>
</html>

ManageNotes/Views/Shared/_spinner.cshtml
@model string
<div id="@Model" style="display: none">
    <div class="sk-circle">
        <div class="sk-circle1 sk-child"></div>
        <div class="sk-circle2 sk-child"></div>
        <div class="sk-circle3 sk-child"></div>
        <div class="sk-circle4 sk-child"></div>
        <div class="sk-circle5 sk-child"></div>
        <div class="sk-circle6 sk-child"></div>
        <div class="sk-circle7 sk-child"></div>
        <div class="sk-circle8 sk-child"></div>
        <div class="sk-circle9 sk-child"></div>
        <div class="sk-circle10 sk-child"></div>
        <div class="sk-circle11 sk-child"></div>
        <div class="sk-circle12 sk-child"></div>
    </div>
</div>
            <!-- width: 70px;height: 35px;  -->